### ISSUE TITLE
This project should not be a tutorial

### ISSUE THREAD

**Issue by antron3000** [KedarKshatriya/BDUofficialNFT#1]
git clone repo should be in the readme

The hardhat project should already have been created, so not necessary to create one again. 

Also, once hardhat is included in the project dependencies, only npm install is necessary

And this is not a tutorial anymore :)

**Comment by KedarKshatriya** [comment]
Thanks for the review.
Fixed here: 7f46534415b12856947b4e19d19b399e719c4f1d
